namespace libtcod_net;

public enum TCOD_fov_algorithm_t
{
    FOV_BASIC,
    FOV_DIAMOND,
    FOV_SHADOW,
    FOV_PERMISSIVE_0,
    FOV_PERMISSIVE_1,
    FOV_PERMISSIVE_2,
    FOV_PERMISSIVE_3,
    FOV_PERMISSIVE_4,
    FOV_PERMISSIVE_5,
    FOV_PERMISSIVE_6,
    FOV_PERMISSIVE_7,
    FOV_PERMISSIVE_8,
    FOV_RESTRICTIVE,
    FOV_SYMMETRIC_SHADOWCAST,
    NB_FOV_ALGORITHMS,
}
