namespace libtcod_net;

public enum TCOD_distribution_t
{
    TCOD_DISTRIBUTION_LINEAR,
    TCOD_DISTRIBUTION_GAUSSIAN,
    TCOD_DISTRIBUTION_GAUSSIAN_RANGE,
    TCOD_DISTRIBUTION_GAUSSIAN_INVERSE,
    TCOD_DISTRIBUTION_GAUSSIAN_RANGE_INVERSE,
}
